
name: 'Terraform Destroy - Dev Sandbox'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: 'destroy'
        type: choice
        options:
          - destroy

env:
  TF_VERSION: '1.5.0'
  AWS_REGION: 'us-east-1'
  TERRAFORM_DIR: 'environments/dev-sandbox'

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: dev-sandbox

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TERRAFORM_DIR }}

      - name: Output Results
        run: |
          echo "## Terraform Destroy Results" >> $GITHUB_STEP_SUMMARY
          echo "Resources destroyed successfully" >> $GITHUB_STEP_SUMMARY
        working-directory: ${{ env.TERRAFORM_DIR }}
